export const celoClickerABI = [
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'player', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'points', type: 'uint256' },
    ],
    name: 'AutoClickerClaimed',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'player', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'points', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'totalPoints', type: 'uint256' },
    ],
    name: 'Clicked',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'player', type: 'address' },
    ],
    name: 'NewPlayer',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'player', type: 'address' },
      { indexed: false, internalType: 'string', name: 'upgradeType', type: 'string' },
      { indexed: false, internalType: 'uint256', name: 'level', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'cost', type: 'uint256' },
    ],
    name: 'UpgradePurchased',
    type: 'event',
  },
  {
    inputs: [],
    name: 'AUTOCLICKER_BASE_COST',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'AUTOCLICKER_INTERVAL',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'AUTOCLICKER_POINTS_PER_LEVEL',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'CLICK_POWER_BASE_COST',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'COST_DENOMINATOR',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'COST_MULTIPLIER',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MULTIPLIER_BASE_COST',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'baseCost', type: 'uint256' },
      { internalType: 'uint256', name: 'currentLevel', type: 'uint256' },
    ],
    name: 'calculateUpgradeCost',
    outputs: [{ internalType: 'uint256', name: 'cost', type: 'uint256' }],
    stateMutability: 'pure',
    type: 'function',
  },
  {
    inputs: [],
    name: 'claimAutoClicker',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'click',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getGlobalStats',
    outputs: [
      { internalType: 'uint256', name: '_totalClicks', type: 'uint256' },
      { internalType: 'uint256', name: '_totalPlayers', type: 'uint256' },
      { internalType: 'uint256', name: '_totalPoints', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getLeaderboard',
    outputs: [
      { internalType: 'address[10]', name: 'addresses', type: 'address[10]' },
      { internalType: 'uint256[10]', name: 'points', type: 'uint256[10]' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'playerAddress', type: 'address' }],
    name: 'getPendingAutoClicker',
    outputs: [{ internalType: 'uint256', name: 'points', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'playerAddress', type: 'address' }],
    name: 'getPlayer',
    outputs: [
      { internalType: 'uint256', name: 'points', type: 'uint256' },
      { internalType: 'uint256', name: 'clickPower', type: 'uint256' },
      { internalType: 'uint256', name: 'autoClickerLevel', type: 'uint256' },
      { internalType: 'uint256', name: 'multiplierLevel', type: 'uint256' },
      { internalType: 'uint256', name: 'totalClicks', type: 'uint256' },
      { internalType: 'uint256', name: 'gamesPlayed', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'playerAddress', type: 'address' }],
    name: 'getUpgradeCosts',
    outputs: [
      { internalType: 'uint256', name: 'clickPowerCost', type: 'uint256' },
      { internalType: 'uint256', name: 'autoClickerCost', type: 'uint256' },
      { internalType: 'uint256', name: 'multiplierCost', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'hasPlayed',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'playerList',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'players',
    outputs: [
      { internalType: 'uint256', name: 'points', type: 'uint256' },
      { internalType: 'uint256', name: 'clickPower', type: 'uint256' },
      { internalType: 'uint256', name: 'autoClickerLevel', type: 'uint256' },
      { internalType: 'uint256', name: 'multiplierLevel', type: 'uint256' },
      { internalType: 'uint256', name: 'lastClaimTime', type: 'uint256' },
      { internalType: 'uint256', name: 'totalClicks', type: 'uint256' },
      { internalType: 'uint256', name: 'gamesPlayed', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'resetPlayer',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalClicks',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalPlayers',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalPoints',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'upgradeAutoClicker',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'upgradeClickPower',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'upgradeMultiplier',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
] as const
